services:
  # ==== 1. The Gateway (Public Face) ====
  # Only THIS service has permission to open ports.
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80" # Web Traffic (Browser/Postman)
      - "27017:27017" # Data Traffic (Compass/TablePlus)
    volumes:
      # Web overwrite the default config entirely
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - mongo

  # ==== 2. The API Fleet (Private) ====
  api:
    build: .
    restart: always
    environment:
      SEEDER_URL: "http://seeder:8081"
      MONGO_URI: "mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo:27017"
    volumes:
      - .:/app
      - /app/tmp #Prevent tmp syncing
    depends_on:
      mongo:
        condition: service_healthy
    command: ["air", "-c", ".air.api.toml"]

  # ==== 3. Seeder ====
  seeder:
    build: . # Uses the SAME Dockerfile!
    environment:
      API_QUEUE_URL: "http://api:8080"
      G_SEARCH: ${G_SEARCH}
      G_CX: ${G_CX}
      USE_DYNAMIC_SEARCH: "true"
    volumes:
      - .:/app
      - /app/tmp
    depends_on:
      api:
        condition: service_started
    command: ["air", "-c", ".air.seeder.toml"]

  # 4. Mongo DB.
  mongo:
    image: mongo:8.2.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "-u",
          "root",
          "-p",
          "example",
          "--authenticationDatabase",
          "admin",
          "--eval",
          "db.adminCommand('ping')",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 60s

  # 5. postgresql
  postgres:
    image: postgres:18.1
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mongo_data:
  postgres_data:
